### ISSUE TITLE
Expose GSP Boundaries as GeoJSON

### ISSUE THREAD

**Issue by flowirtz** [openclimatefix/nowcasting_api#50]
We need to expose the [GSP GIS Boundaries (public domain)](https://data.nationalgrideso.com/system/gis-boundaries-for-gb-grid-supply-points) via our API, to make sure we are always using the same version of it across the application.

If not already in that shape, they should be [exposed in the GeoJSON format](https://geojson.org/), in line with our other endpoints returning JSON as well.

A possible endpoint for this could be:
```text
GET /shapes/GB/gsp
```

**Comment by peterdudfield** [comment]
Let me know when/if this is blocking you @flowirtz and ill bump it up my list

**Comment by JackKelly** [comment]
Do we know if the front-end mapping code can handle geospatial coordinates in the OSGB coordinate reference system? If not, I guess the Python code should convert the OSGB coordinates to WGS84 (i.e. convert to latitude and longitude)?

In fact, in anticipation of providing forecasts for other parts of the world, maybe we should standardise on WGS84 now (because OSGB is only well defined for Great Britain).

**Comment by peterdudfield** [comment]
It seem to plot ok in this [code](https://github.com/openclimatefix/nowcasting_dataset/blob/main/notebooks/2021-09/2021-09-07/gsp.py)

![Screenshot 2022-01-27 at 15 56 14](https://user-images.githubusercontent.com/34686298/151395044-5c528c73-e955-4d64-80fe-9ccab9cab477.png)

This code is using WGS84

**Comment by peterdudfield** [comment]
Im not sure on the orginally format, but it is easily moved to WGS84

```

import itertools
import json
from urllib.request import urlopen

import geopandas as gpd
import numpy as np
import plotly.graph_objects as go

WGS84_CRS = "EPSG:4326"

# get file
url = (
    "https://data.nationalgrideso.com/backend/dataset/2810092e-d4b2-472f-b955-d8bea01f9ec0/resource/"
    "a3ed5711-407a-42a9-a63a-011615eea7e0/download/gsp_regions_20181031.geojson"
)

with urlopen(url) as response:
    shapes_gdp = gpd.read_file(response).to_crs(WGS84_CRS)
```

**Comment by flowirtz** [comment]
I agree with @JackKelly that it would be better to use the lat/lon format as it works outside the UK as well, especially if it's not a lot of work to transform.

Looking at [`get_gsp_shape_from_eso`](https://github.com/openclimatefix/nowcasting_dataset/blob/2bf522eb4882e2f9d31888b700996723e9fc7051/nowcasting_dataset/data_sources/gsp/eso.py?_pjax=%23js-repo-pjax-container%2C%20div%5Bitemtype%3D%22http%3A%2F%2Fschema.org%2FSoftwareSourceCode%22%5D%20main%2C%20%5Bdata-pjax-container%5D#L117) it looks like that's not using WGS84, at least there is a comment in the code saying that.



Btw, what coordinate system are we using to train our models?

**Comment by JackKelly** [comment]
> Btw, what coordinate system are we using to train our models?

We're currently using OSGB.

@jacobbieker and I have briefly discussed which coordinate reference system we should use for training our models when we start training across the whole geographical extent of the EUMETSAT SEVIRI imagery. Our preliminary conclusion is to continue using OSGB because the errors outside the UK are pretty tiny and it minimises the amount of work (I forgot how tiny the errors... I think it was just a few meters... is that right @jacobbieker?)

But it'd be fairly easy to use a different coordinate reference system for training our models.  Crucially, the new intermediate satellite Zarrs store the coordinates in the original "geostationary" coordinate reference system, so we can convert to any other CRS.

**Comment by jacobbieker** [comment]
Yeah, the error on OSGB I think should be like 7 meters or something like that? Its essentially a shifted WGS84 coordinate system apparently.

**Comment by JackKelly** [comment]
On the topic of whether OSGB coordinates are safe to use outside of Great Britain... I finally got round to following Jacob's recommendation and reading the [Wikipedia article on OSGB](https://en.wikipedia.org/wiki/Ordnance_Survey_National_Grid#Compatibility_with_related_systems) (especially the section on "compatibility with related systems") and, unless I've misunderstood, the text is a little ambiguous as the whether the "7 meter" error is typical _across the whole globe_, or _just_ across GB (and so the error might be a lot more away from GB). Most of the text appears to be talking about GB, so I'd guess it's likely that the 7 meter error is just over GB?

So, yeah, maybe we should be standardising on WGS 84 coordinates in our training code and our production code. What do you think @jacobbieker

**Comment by jacobbieker** [comment]
This AU gov site seems to suggest the error for WGS84 is 2-5 meters for Australia at least, so I would assume that should hold worldwide? https://www.ga.gov.au/scientific-topics/positioning-navigation/wgs84 , but yeah, I'm not entirely sure the error of the coordinate system. Since we are planning on doing things outside of just the UK, maybe using WGS84 makes more sense then, as its more stnadardized.
